### ISSUE TITLE
[Init] 프로젝트 초기세팅

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#1]
## ISSUE
- 프로젝트 기초세팅

## To-do
- [x] git ignore 세팅
- [x] gradle 기초세팅
- [x] color/font설정
- [x] logo이미지 drawable폴더에 추가(img_yourweatherlogo)
- [x] package 구조 설정
- [x] issue 템플릿 생성
- [x] pull request 템플릿 생성
- [x] project 탭 생성
- [x] 라벨설정

## 참고사항 및 체크포인트
각종 블로그들 인데 .. 아무튼 그렇습니당 ㅠ
