### ISSUE TITLE
[refactor]캘린더뷰 디테일 수정

### ISSUE THREAD

**Issue by PicturePark1101** [yourweather/yourweather_android#101]
## ISSUE
- 캘린더뷰 디테일 수정

## To-do
- [x] 상단 폰트 변경
- [x] 선택창 폰트 변경
- [x] 상단 아이콘 추가
- [x] 이동 창 바로 이동 되도록 수정
