### ISSUE TITLE
[refactor] 캘린더 상세보기 코드 수정

### ISSUE THREAD

**Issue by hyemyu** [yourweather/yourweather_android#105]
## ISSUE
- 캘린더 상세보기 코드 수정

## To-do
- [x] 스크롤뷰 비율 수정
- [x] 꺾은선 그래프 이미지 추가
- [x] 뷰 연결 액티비티 내용 추가
- [x] 수평스크롤뷰 레이아웃 전부 수정

## 참고사항 및 체크포인트
시간 문제 상 꺾은 선 그래프를 전부 이미지로 넣었는데...바로 기능 코드들로 수정할 예정입니다..!(영상시현 때문에 어쩔 수 없이 이미지로 대체했습니닷..)
