### ISSUE TITLE
[refactor] 홈화면 프래그먼트로 변경 / 홈-날씨입력창 뷰 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#112]
## ISSUE
- 홈화면 프래그먼트로 변경 / 홈-날씨입력창 뷰 수정

## To-do
- [x] 홈화면 프래그먼트로 변경
- [x] seekbar 0º 위치 오른쪽으로 좀 더 이동
- [x] 홈화면 온도 와 단위 각각 다른 폰트 (숫자만 한나체로 변경)
- [x] 토스트 메시지 폰트 ( pretendard semibold로 변경)
