### ISSUE TITLE
[refactor] 비교분석뷰 프래그먼트로 변경

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#113]
## ISSUE
- [refactor] 비교분석뷰 프래그먼트로 변경

## To-do
- [x] 비교분석뷰 프래그먼트로 변경
- [x] 미입력 내역 프래그먼트로 변경
- [x] 미입력 내역 모두 완료 되었어요 창 프래그먼트로 변경
- [x] 각 아이콘 별 상세보기 프래그먼트로 변경 (주간 - 맑음, 비, 번개, 흐림 / 월간 - 맑음, 배, 번개, 흐림)
