### ISSUE TITLE
[add] comparison analysis view 

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#12]
## ISSUE
- [feat] comparison analysis view 

## To-do
- [x] 비교분석 틀 뷰 (타이틀, ic_bell, 주간 / 월간 전환 버튼)
- [x] 주간, 월간 버튼
- [x] 월간 날씨
   - [x] 비교 분석 데이터 (bar 형태) 프래그먼트
   - [x] 아이콘 별 데이터 프래그먼트 

- [x] 주간 날씨
   - [x] 비교 분석 데이터 (bar 형태) 프래그먼트
   - [x] 아이콘 별 데이터 프래그먼트 
   
- [x] 네비게이션 바 적용

- [x] 각 아이콘 기록 시간 (리포트 버튼 클릭 시) 뷰 생성 및 연결
   - [x] sun
   - [x] cloud
   - [x] rain
   - [x] thunder

- [x] 모든 기록을 완료했어요 뷰
- [x] 미입력 내역 존재 시 리사이클러 뷰

- [x] 피그마와 비율 똑같이 구현

---

## 참고사항 및 체크포인트
미입력 내용 화면 구현 필요
신체 날씨 기능 부분 제거
