### ISSUE TITLE
[feat] 날씨입력창 날씨아이콘 클릭 이벤트 추가

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#138]
## ISSUE
- 날씨입력창 날씨아이콘 클릭 이벤트 추가

## To-do
- [x] 각 날씨아이콘 클릭 시 확대되는 애니메이션 적용
- [x] 클릭된 상태에서 다른 날씨 클릭 시 먼저 누른 아이콘 원상복귀
- [x] 클릭 시 크기 1.0 -> 1.5 (ani->btn_weather_scale.xml에 정의)

## 참고사항 및 체크포인트
캘린더 상세보기 페이지에서도 같은 내용 사용될 예정

**Comment by yeriinnn** [comment]
메인에 merge 완료
