### ISSUE TITLE
[style]소셜 로그인 버튼 크기조정/로그인뷰 세부사항 수정

### ISSUE THREAD

**Issue by ParkSeojin1101** [yourweather/yourweather_android#143]
## ISSUE
- 소셜 로그인 버튼 크기조정

## To-do
- [x] 소셜 로그인 버튼 크기조정
- [x] 이동 로직 추가(닉네임뷰->초기화면)
- [x] 로그인뷰에서 토스트 주석처리
