### ISSUE TITLE
[refactor]로그인 뷰 디자인 수정

### ISSUE THREAD

**Issue by PicturePark1101** [yourweather/yourweather_android#16]
## ISSUE
로그인 뷰 디자인 다시 체크하고 수정(비율, 버튼 크기 등등)

## To-do
- [x] "유어웨더 자체로그인" editText 비율 조정
- [x] 버튼 크기 알맞는지 다시 확인하기 
- [x] 수정된 디자인대로 다시 수정

## 참고사항 및 체크포인트
피그마 화면보다 에뮬레이터 화면이 짧아서 임의로 배치했는데 괜찮은지 다른분들과 의논해보고 싶습니다.
