### ISSUE TITLE
[setting] 서버 연결 세팅

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#167]
## ISSUE
- 서버 연결 세팅

## To-do
- [x] 공통 DTO 생성 
- [x] service 패키지 생성 후 controller단위 인터페이스 생성
- [x]  @SerializedName 태그 추가
- [x]  패키지 구조 이동

## 참고사항 및 체크포인트
repository 항목 내에 들어갈 ~repository 및 ~repositoryImpl 의 경우 우리 수준에서 사용가능 여부에 대해 먼저 결정해야 할듯 !
