### ISSUE TITLE
[feat] 마이페이지 첫 화면 재구성

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#170]
## ISSUE
- 마이페이지 첫 화면 재구성

## To-do
- [x] activity -> fragment로 변경
- [x] 규격 및 rule에 맞춰 전체 재수정 
- [x] bnv 추가
- [x] 바텀네비에서 마이페이지 클릭 시 해당 화면으로 이동하는 기능 추가

**Comment by yeriinnn** [comment]
메인에 merge 완료
