### ISSUE TITLE
[feat] 마이페이지 내의 뷰 전환 기능 추가

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#173]
## ISSUE
- 마이페이지 내의 뷰 전환 기능 추가

## To-do
- [ ] iv_my_page_next_info 클릭 시 "내 정보" 뷰 이동
- [ ] 알림설정(tv_my_page_alarm) 클릭 시 "알림 설정" 뷰 이동
- [ ] 이벤트날씨설정(tv_my_page_event_weather) 클릭 시 "이벤트 기록 설정" 뷰 이동
- [ ] 이용약관(tv_my_page_terms) 클릭 시 이용약관 띄우기
- [ ] 개인정보 처리방침(tv_my_page_policy) 클릭 시 개인정보 처리방침 내용 띄우기

## 참고사항 및 체크포인트
to-do에 해당되는 각 뷰 완료되는 대로 추가할 예정
