### ISSUE TITLE
[refactor] 마이페이지 첫 번째 뷰 전반적인 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#174]
## ISSUE
- 마이페지이 첫 번째 뷰 전반적인 수정

## To-do
- [x] title, 이메일 폰트 및 색상 수정
- [x] 각 구성 항목의 너비 재설정 
- [x] user 관련 첫 번째 부분 위치 재조정

**Comment by yeriinnn** [comment]
메인에 머지완료
