### ISSUE TITLE
[add] 미입력 내역 뷰

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#19]
## ISSUE
- 미입력내역 뷰 구현

## To-do
- [x] 미입력 내용 미존재 시 화면  (fragment)
- [ ] 미입력 내용 존재 시 화면 (Recyclerview 활용 / fragment)
- [ ] 피그마와 비율 똑같이 구현
