### ISSUE TITLE
[feat] 회원가입 로직 이메일, 비밀번호, 플랫폼 값 닉네임으로 넘겨주기

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#219]
## ISSUE
- [feat] 회원가입 로직 이메일, 비밀번호, 플랫폼 값 닉네임으로 넘겨주기

## To-do
- [x] 회원가입 로직 이메일, 비밀번호, 플랫폼 값 닉네임으로 넘겨주기
- [x] 이메일 -> 비밀번호 입력으로 
- [x] 비밀번호, 이메일 -> 닉네임으로 
- [x] 닉네임 파일 : 이메일, 비밀번호 값 받아오기 + 자체 회원가입 함수 구현

**Comment by kangyuri1114** [comment]
메인에 머지됨
