### ISSUE TITLE
[feat] 랜덤 닉네임 구현 코드 추가

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#22]
## ISSUE
- 랜덤 닉네임 구현 코드 추가

## To-do
1. 기능 구현
- [x] 랜덤 닉네임 구현 코드 추가
- [x] 유저가 해당 칸 클릭 시 공백이 되면서 사용자가 입력하는 값 받기

1-1. 새로고침 버튼에 대한 이벤트흐름
- [x] 회색 글씨 상태에서 클릭 시 랜덤으로 닉네임 변경
- [x] 유저가 텍스트 입력 도중 새로고침 누를 시 입력하던 텍스트 모두 없어지고 위의 항목대로 실행
2. 뷰 구현
- [x] '새로 고침'버튼 추가
- [x] 다음 버튼 변경 

## 참고사항 및 체크포인트
유저가 설정한 닉네임 또는 자동으로 추천받은 닉네임 "저장" 관련 구현은
백엔드와 api연결 시 이루어질 예정
