### ISSUE TITLE
[refactor] 비교분석 뷰 수정

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#221]
## ISSUE
- 비교분석 뷰 수정 Constraint 로 

## To-do
- [x] 각 날씨별 디테일 뷰끼리 Constraint 묶기
- [x] 리포트 글씨체 변경
- [x] 각 날씨별 디테일 뷰에서 버튼이 아닌 리니어 레이아웃 클릭 시 화면 전환
- [x] 버튼 클릭 가능 범위 늘리기

**Comment by kangyuri1114** [comment]
머지됨
