### ISSUE TITLE
[feat] 회원가입 api 기능 구현

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#227]
## ISSUE
- 회원가입 api 기능 구현

## To-do
- [x] 유저가 설정한 닉네임 값 고정되게 하기
- [x] (유저가 설정한 닉네임 제외) 랜덤 닉네임 사용하는 경우 해당 닉네임 값 고정되게 하기 
- [x] 랜덤닉네임 설정 창에서 회원가입 api 기능 붙이기

**Comment by yeriinnn** [comment]
메인에 머지완료
