### ISSUE TITLE
[add] 홈 화면 뷰 구현

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#23]
## ISSUE
- 홈 화면 뷰 구현

## To-do
1. 홈 화면에서 감정 날씨 입력 받는 뷰 구현
- [x] 날씨 아이콘
- [x] 감정 온도(seekbar)
- [x] 메모입력
- [x] 각종 버튼 및 textview

2. 그라데이션 배경 이미지 삽입
- [x] 기본 화면 '맑음'으로 지정

3. 모션 그래픽 영상 
- [x] 기본 영상 '맑음'으로 지정

## 참고사항 및 체크포인트
유저가 설정한 날씨에 다른 배경이미지와 영상 전환은 api 연결시 진행 예정
