### ISSUE TITLE
[refactor] 홈화면,날씨입력창 뷰 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#240]
## ISSUE
- 홈화면, 날씨입력창 뷰 수정

## To-do
- [x] 홈화면 광고뷰 닫기 버튼 위치 조정 및 클릭 범위 확대
- [x] 홈화면 텍스트뷰 조정(겹치는 것 방지)
- [x] 홈화면 광고뷰 크기 조정
- [x] 날씨입력창 뷰 배경 이미지 변경
- [x] 날씨입력창 뷰 저장, x 버튼 위치 조정 및 클릭 범위 확대
- [x] 토스트메시지 위치조정

**Comment by yeriinnn** [comment]
메인에 머지완료
