### ISSUE TITLE
[demo] 토요일 전까지는 끝내야 하는 거............

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#242]
## ISSUE
- [demo] 토요일 전까지는 끝내야 하는 거............

## To-do
<1. API 붙일 때 할 것>

미입력 내역 
- [ ] API에서 받아온 값으로 텍스트, 색 변환, 화살표
- [ ] 미입력 내역 있을 때의 종 파일 변환
- [ ] API로 받아와서 각각 날씨 상세 보기 구현
- [ ] 각 상세 리스트에서 오늘 주, 월로 텍스트 변경 몇회인지 구현
- [ ] 미입력 리스트 띄워주기
- [ ] 미입력 내역 몇회인지 구현

그외
- [ ] 자동로그인 구현

<2. API 없이 할 수 있는 기능>
- [ ] 마이페이지 알림 기능 구현 - notification
- [ ] 각 상세 리스트에서 현재 주, 월로 텍스트 변경

<3. 뷰 수정>
- [ ] 말풍선 위치 조정 (중요..)
- [ ] 디테일뷰에서 캘린더 넘어가는 거 연결 (캘린더 상세보기가 메인에 머지되어야 함 / - 디테일뷰 구조 변경)
- [ ] 뷰 구조 수정 (비율코딩 적용 안 된 곳)
- [ ] 버튼 터치 영역크게

## 참고사항 및 체크포인트
마땅히 써둘 곳이 없어서.. 제 메모장으로 잠깐 쓸게용... 나중에 지울거라 demo로 합니다..
