### ISSUE TITLE
[feat] 홈-날씨입력창 api 기능 구현

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#244]
## ISSUE
- 홈-날씨입력창 api 기능 구현

## To-do
- [x] 홈화면 api 기능 구현
- [x] 날씨입력창 api 기능 구현
- [x]  홈화면 닉네임 변경 기능 구현
- [x] 홈화면 모션영상 변경 기능 구현
- [x] 홈화면 날씨 설명 변경 기능 구현
- [x] 홈화면 온도 변경 기능 구현
- [x] status enum class로 분기
