### ISSUE TITLE
[feat] 비교분석 bar 통계 부분 API 붙이기 

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#249]
## ISSUE
- 비교분석 bar 통계 부분 API 붙이기 

## To-do
- [x]  주간 통계 api 받아오기 성공
- [x]  월간 통계 api 받아오기 성공
- [x] 주간 데이터 비교 api 받아오기 성공
- [x] 월간 데이터 비교 api 받아오기 성공
- [x] 이번 달/주, 저번 달/주 정확하게 나오도록 구현

**Comment by kangyuri1114** [comment]
메인에 머지됨
