### ISSUE TITLE
[refactor] 홈화면 뷰 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#265]
## ISSUE
- 홈화면 뷰 수정

## To-do
- [ ] 광고 뷰 닫는 버튼 위치 조정
- [ ] "닉네임"과 "의 감정날씨" 부분 위치 조정
- [ ]  모션영상 잘림 현상 수정(비, 번개 영상 윗부분 잘림)
