### ISSUE TITLE
[feat] 비교분석뷰 날씨별 상세 보기 리스트 API 붙이기

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#266]
## ISSUE
- [feat] 비교분석뷰 날씨별 상세 보기 리스트 API 붙이기

## To-do
- [x] 비교분석뷰 날씨별 상세 보기 리스트 API 붙이기
- [x] 오늘 날짜 기준으로 전주, 전달에 대한 값들 유동적으로 보일 수 있게 적용
- [x] 각 주, 각 월마다의 각 날씨의 값을 받아올 수 있게 API 붙임

**Comment by kangyuri1114** [comment]
메인에 머지됨
