### ISSUE TITLE
[feat] 마이페이지 API 붙이기

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#296]
## ISSUE
- [feat] 마이페이지 API 붙이기

## To-do
- [x] 아미페이지에 유저정보 불러와서 화면에 띄우기 - 닉네임, 이메일, 플랫폼 보여주기
- [x] 내정보 화면에 유저 정보 띄우기
- [x] 닉네임 변경 API
- [x] 비밀번호 변경 API
- [x] 뷰 연결

**Comment by kangyuri1114** [comment]
머지됨
