### ISSUE TITLE
[feat] 홈-날씨입력창 기능 추가 및 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#308]
## ISSUE
- 홈-날씨입력창 기능 추가 및 수정

## To-do
- [x]  광고뷰 삭제 기능 추가
- [x] gif 잘림현상 수정
- [x] 그라데이션 배경 네임 전체적으로 변경 
- [x] 홈화면 전반적인 뷰 수정
- [x] 유저 닉네임 불러오기_initial뷰
- [x] 유저 닉네임 불러오기_weatheri뷰
- [x] seekbar thumb클릭시 온도 보여주기
