### ISSUE TITLE
[setting] 앱 기초 세팅

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#346]
## ISSUE
- 앱 기초 세팅

## To-do
- [x] 다크모드 비활성화 설정
- [x] 화면 전환 막기(세로모드만 허용)
- [x] 네임 컨벤션 미준수 파일명 변경
- [x] 불필요한 xml 제거
