### ISSUE TITLE
[add] 캘린더 상세보기 창 구현

### ISSUE THREAD

**Issue by PicturePark1101** [yourweather/yourweather_android#369]
## ISSUE
- 캘린더 상세보기 창 구현

## To-do
- [x] 캘린더 상세보기 창 구현
- [ ] 기존 파일들 삭제
- [ ] actionbar 적용해보기
- [ ] 리사이클러뷰로 구현할 것 
- [ ] api 연결해서 확인
