### ISSUE TITLE
[fix/feat] 홈 화면 강제종료 수정 및 카메라 권한 설정 기능 구현

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#376]
## ISSUE
- 홈 화면 강제종료 수정 및 카메라 권한 설정 기능 구현

## To-do
- [x] 홈화면 강제 종료 오류 수정
- [x] 카메라 권한 설정 뷰 구현
- [x] 카메라 권한 여부 메시지 출력 기능 구현
- [x] 공유버튼 클릭 시 창 띄우는 기능 구현

## 참고사항 및 체크포인트
커밋이 꼬여서 ... 이렇게 두 가지 기능을 한 번에 올리게 되었습니당...
