### ISSUE TITLE
[fix] 홈 화면 캡쳐 기능 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#383]
## ISSUE
- 홈 화면 캡쳐 기능 수정

## To-do
- [x] 캡쳐 시 불필요한 항목 제거
- [x] 최신 aos 에서 캡쳐 불가한 점 반영하여 기능 수정
- [x] 캡쳐 후 홈화면 필요한 뷰들 띄우는 기능 수정
