### ISSUE TITLE
[refactor] 날씨입력창 및 기타 뷰 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#407]
## ISSUE
- 날씨입력창 및 기타 뷰 수정

## To-do
- [x] 날씨입력창 온도 값 배경 이미지 변경(말풍선->사각형)
- [x] 카메라 허용 부분 가이드 이미지 변경(png->svg)
- [x] 회원가입 비밀번호 입력 가이드 메시지 변경(대소문자->영문자)
