### ISSUE TITLE
[refactor] 스플래시 뷰 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#68]
## ISSUE
- 스플래시 뷰 수정

## To-do
- [x] bm한나체로 폰트 수정
- [x] 뷰 재배치(위치조정)
- [x] 텍스트 사이즈 변경
- [x] 텍스트 색상 변경
