### ISSUE TITLE
[refactor] bottomnavigation 수정

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#70]
## ISSUE
- bottomnavigation 수정

## To-do
- [x] 바텀네비 높이 수정 (56) 
- [x] 바텀네비 배경색 및 테두리 변경
- [x] 바텀네비 아이콘 미클릭/클릭 시의 색상 변경

## 참고사항 및 체크포인트
바텀네비에 들어가는 항목들을 각각의 fragment로 둘 필요가 있는지 의논 필요!
