### ISSUE TITLE
[demo] 홈화면-날씨입력 데모영상 로직

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather_android#92]
## ISSUE
- 홈화면-날씨입력 데모영상 로직

## To-do
- [x] 기본날씨 맑음에서 흐림선택 후 맑음+흐림 그라데이션 배경으로 홈화면 변경
- [x] 설정한 온도 값으로 홈화면 변경
- [x] 흐림으로 모션 영상 변경
- [x] 설정한 온도에 따라 온도 변경

## 참고사항 및 체크포인트
날씨 아이콘 선택에 따른 이벤트의 해결책을 빨리 찾고싶당...^_^

**Comment by yeriinnn** [comment]
수정사항이 생겨 진행할 필요가 없어진 이슈입니다.

데모영상 홈화면-날씨입력창 로직 : initial뷰 -> 날씨입력창에서 맑음 클릭 후 저장 -> 홈화면 맑음으로 변경

현재 해당 부분 구현 완료 후 main에 merge된 상태입니다.
